spring:
  datasource:
    name: druid
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/plugin_market?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123456
mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名匹配映射